### PR TITLE
Sqlite foreign keys

### PR DESCRIPTION
**Pull request by ctSkennerton**
Increased support for SQLite by adding foreign key constraints to the database to bring it inline with the other databases and updated the `load_ncbi_taxonomy.pl` script to support SQLite

### CODE REVIEW

**Comment by peterjc** [comment]
Positive comments from the original SQLite schema author @chapmanb on https://github.com/biopython/biopython/pull/743#issuecomment-168214428 (applying same changes to Biopython).

What do you think @hlapp? Note this also adds SQLite support to ``load_ncbi_taxonomy.pl`` which is useful.

**Comment by hlapp** [comment]
Hi @ctSkennerton - this is great. I notice that a lot if not the majority of the diff is whitespace changes, which makes it difficult to see what actually changed. Given that the whitespace changes are so extensive, I assume it's the result of a setting of the editor you are using. If it's not too hard for you to reset the whitespace changes that'd be great. Otherwise I can try and do this by hand on the command line.

**Comment by ctSkennerton** [comment]
Hi @hlapp. sorry for that. Github has a handy feature to [look at diffs without considering whitespace](https://github.com/blog/967-github-secrets). Below is links to the commits with this applied:

[added support for SQLite](https://github.com/ctSkennerton/biosql/commit/8dba7fb5aa23f64b24ed94f8253fb3f1c691570c?w=1)
[add foreign keys to sqlite3 database schema](https://github.com/ctSkennerton/biosql/commit/81863617841561309e3f92ef210e3e0695c91f7f?w=1)

**Comment by hlapp** [comment]
Thanks for the tip, @ctSkennerton, very useful! I notice that you didn't include in the `biosqldb-sqlite.sql` changes the statement `PRAGMA foreign_keys = ON` that you do include in the `load-ncbitaxonomy.pl` script. Shouldn't that be included in the schema DDL as well, or is that somehow turned on there automatically? Sorry, I rarely ever use SQlite, so am not very knowledgable about how it does things.

**Comment by ctSkennerton** [comment]
SQLite doesn't enforce foreign keys by default, even when they are defined in the schema, this is for backwards compatibility with very old versions of the database. Therefore the user has to enable foreign keys at run time for every connection. So putting the pragma in the schema itself does not do anything.

**Comment by hlapp** [comment]
I merged this with whitespace-only changes removed. Your modified commits are 1af8fd7d1ae9c1de86ae0810200dd2454ee5513f and 297ff52ed87050c0032bee4f43809ccaa241a218.

**Comment by ctSkennerton** [comment]
great thanks!

**Comment by peterjc** [comment]
Does it make sense to put the pragma in the schema with a comment?

**Comment by hlapp** [comment]
> Does it make sense to put the pragma in the schema with a comment?

Good suggestion. Pull request?

**Pull request closed without merging**
